### ISSUE TITLE
Missing Python Dependency

### ISSUE THREAD

**Issue by l4rm4nd** [Pepelux/sippts#44]
Installation on a fresh Kali Linux instance:

````
git clone https://github.com/Pepelux/sippts
cd sippts
virtualvenv venv
source venv/bin/activate

pip install .
````

Installation succeeds but running sippts leads to the following error:

````
└─$ sippts                                                                                                              
Traceback (most recent call last):
  File "/home/user/Documents/sippts/venv/bin/sippts", line 10, in <module>
    from sippts.lib.params import get_sippts_args
  File "/home/user/Documents/sippts/venv/lib/python3.11/site-packages/sippts/lib/params.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
````

Easily resolved by installing requests via pip:

````
pip install requests
````

Please add `requests` to the `setup.py`.

Cheers.

**Comment by Pepelux** [comment]
You can try it using the deb packages:
https://bugs.kali.org/view.php?id=4863#c19550

In the next version of Kali it will be integrated

Cheers
